fix: rename block to timestamp.
unioncredit/union-v2-contracts pull request #155
Opened 2023-04-20 07:48 UTC by twygod

Fix the issue mentioned by dmitriia in feature/uni-1339-update-lookup-table-in-comptroller but not modified

2023-04-20 09:50 UTC, maxweng requested changes

2023-04-20 09:50 UTC, maxweng commented on deployments/goerli/config.json
> +        "interestRatePerBlock": "3170979198"
Should this one be `interestRatePerSecond`?

2023-04-20 11:49 UTC, kingjacob commented on contracts/asset/AssetManager.sol
Compound and aave arent denominated in seconds

2023-04-23 03:13 UTC, maxweng approved these changes

2023-04-24 15:25 UTC, GeraldHost approved these changes

2023-04-25 02:08 UTC, merged